version: "2"
checks:
  method-lines:
    enabled: true
    config:
      threshold: 40
plugins:
  bandit:
    enabled: true
    config:
      python_version: 3
  pep8:
    enabled: true
exclude_patterns:
- "**/*.test.js"
- "**/*.test.jsx"
- "**/test/"
