version: "2"
plugins:
  bandit:
    enabled: true
    config:
      python_version: 3
  pep8:
    enabled: true
exclude_patterns:
- "**/*.test.js"
- "**/test/"
similar-code:
    config:
      threshold: 3
