jobs:
  include:
    - stage: python unit tests
      python: "3.6"
      cache:
        directories:
          - $HOME/.cache/pip
      script: echo WIP
    - stage: node_js unit tests
      node_js: "7"
      cache:
        yarn: true
        directories:
          - node_modules
      script: yarn test
    - stage: security tests on python
      script: echo WIP
    - stage: security tests on node_js
      script: echo WIP
    - stage: deploy to staging
      script: echo WIP
    - stage: test staging
      script: 'curl https://staging-kamu.thoughtworks-labs.net' 