cache:
  yarn: true
  directories:
  - "$HOME/.cache/pip"
  - node_modules
jobs:
  include:
  - stage: lint
    language: node_js
    node_js: '7'
    script:
      - yarn lint
  - stage: python unit tests
    language: python
    python: '3.6'
    script: DISABLE_SAML2=true python manage.py test
  - stage: node_js unit tests
    language: node_js
    node_js: '7'
    script: yarn test
  - stage: deploy to staging
    script: skip
    deploy: &script
      provider: script
      script: git remote add deploy $MAINSTREAM && git push -f deploy master
      on:
        branch: master
  - stage: test staging
    script: 'curl --fail $STAGING'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/045b03a1ec92f87761e5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
