cache:
  yarn: true
  directories:
  - "$HOME/.cache/pip"
  - node_modules
jobs:
  include:
  - stage: python unit tests
    language: python
    python: '3.6'
    script: DISABLE_SAML2=true python manage.py test
  - stage: node_js unit tests
    language: node_js
    node_js: '7'
    script: yarn test
  - stage: deploy to staging
    script: skip
    #script: export DISABLE_SAML2=true
    before_deploy: export DISABLE_SAML2=true
    deploy: &script
      provider: script
      #env: DISABLE_SAML2=true
      script: git remote add deploy $MAINSTREAM && git push -f deploy Functional_tests
      on:
        branch: Functional_tests
  - stage: test staging
    #sudo: required
    #language: python
    #python: '3.6'
    #script: DISABLE_SAML2=true python KamuSeleniumTests.py
    script: 'curl $STAGING'
