cache:
  yarn: true
  directories:
    - $HOME/.cache/pip
    - node_modules

jobs:
  include:
    - stage: python unit tests
      language: python
      script: echo WIP
    - stage: javascript unit tests
      language: node_js
      script: yarn test
    - stage: security tests
      script: echo WIP
    - stage: deploy to staging
      script: echo WIP
    - stage: test staging
      script: 'curl https://staging-kamu.thoughtworks-labs.net' 