version: '3'

services:
  web:
    build: .
    image: ayrton/kamu
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://kamu:kamu@database/kamu
      - CELERY_BROKER_URL=redis://redis:6379/0
      - NODE_ENV=production
      - DEBUG=true
      - GUNICORN_CMD_ARGS="--bind=0.0.0.0"
    volumes:
      - ./core:/app/core
      - ./books:/app/books
      - ./config:/app/config
      - ./Makefile:/app/Makefile
      - ./requirements.txt:/app/requirements.txt
      - ./waitlist:/app/waitlist
      - cache:/tmp/cache
      - buildpacks:/tmp/buildpacks
    depends_on:
      - database
      - redis
  worker:
    build: .
    image: ayrton/kamu
    command: ["/start", "worker"]
    environment:
      - DATABASE_URL=postgres://kamu:kamu@database/kamu
      - CELERY_BROKER_URL=redis://redis:6379/0
      - NODE_ENV=production
      - DEBUG=true
      - DJANGO_EMAIL_FROM=${DJANGO_EMAIL_FROM}
      - DJANGO_EMAIL_HOST=${DJANGO_EMAIL_HOST}
      - DJANGO_EMAIL_PORT=${DJANGO_EMAIL_PORT}
      - DJANGO_EMAIL_HOST_USER=${DJANGO_EMAIL_HOST_USER}
      - DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD}
    volumes:
      - ./core:/app/core
      - ./books:/app/books
      - ./config:/app/config
      - ./Makefile:/app/Makefile
      - ./requirements.txt:/app/requirements.txt
      - ./waitlist:/app/waitlist
      - cache:/tmp/cache
      - buildpacks:/tmp/buildpacks
    depends_on:
      - database
      - redis
  database:
    image: postgres
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kamu
      - POSTGRES_PASSWORD=kamu
      - POSTGRES_DB=kamu
  redis:
    image: redis
    expose:
      - 6379

volumes:
  db-data:
  cache:
  buildpacks: