version: '3'

services:
  dev:
    image: kamu_web
    command: npm start
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://kamu:kamu@database/kamu
      - NODE_ENV=development
    volumes:
      - ./kamu:/app/kamu
      - ./dev-server.js:/app/dev-server.js
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./webpack.config.js:/app/webpack.config.js
      - ./assets:/app/assets
      - ./books:/app/books
      - ./config:/app/config
      - ./Makefile:/app/Makefile
      - ./requirements.txt:/app/requirements.txt
      - ./waitlist:/app/waitlist
      - cache:/tmp/cache
      - buildpacks:/tmp/buildpacks 
    depends_on:
      - database