version: '3.7'
services:
  api:
    build:
      context: .
    env_file: docker_env
    depends_on:
      - db
    ports:
      - "8000:8000"
      - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example # postgres/example
