[project]
name = "Kamu"
version = "0.0.2"
requires-python = ">=3.12"
dependencies = [
    "django==5.0.0",
    "grafana-django-saml2-auth>=3.20.0",
    "pysaml2",
    "django-import-export>=2.8.0",
    "dj-database-url>=0.5.0",
    "python-decouple>=3.6",
    "whitenoise>=6.0.0",
    "gunicorn>=20.1.0",
    "psycopg2>=2.9.9",
    "requests>=2.27.1",
    "cryptography>=36.0.1",
    "pyopenssl>=22.0.0",
    "cffi>=1.15.0",
    "coverage>=7.0",
    "flake8>=6.0.0",
    "ipdb>=0.13.9",
    "ipython>=8.1.1",
    "httpretty>=1.1.4",
    "python-dateutil>=2.8.2",
]
[tool.pyright]
include = ["src", "tests"]
exclude = ["**/node_modules", "**/__pycache__", "build", "dist"]
venvPath = "."
venv = ".venv"
pythonVersion = "3.12"
extraPaths = ["./"]
[tool.uv]
package = false
