# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('number_of_pages', models.IntegerField()),
                ('publication_date', models.DateField()),
                ('publisher', models.CharField(max_length=255)),
            ],
        ),
    ]
