# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20170327_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='books',
            field=models.ManyToManyField(through='books.BookCopy', to='books.Book'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='books.Library'),
        ),
    ]
