# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170327_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
