# Generated by Django 2.0.1 on 2019-01-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
        ('books', '0008_bookcopy_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='waitlist_items',
            field=models.ManyToManyField(related_name='waitlist_items', through='waitlist.WaitlistItem', to='books.Book'),
        ),
    ]
