# Generated by Django 2.0.1 on 2019-01-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20190102_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='status',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='state',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('DONE', 'DONE')], default='PENDING', max_length=255),
        ),
    ]
