# Generated by Django 2.2.13 on 2020-10-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_library_waitlist_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='missing',
            field=models.BooleanField(default=False),
        ),
    ]
