# Generated by Django 2.0.1 on 2019-01-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_library_waitlist_items'),
        ('books', '0009_auto_20190107_1959'),
    ]

    operations = [
    ]
