# Generated by Django 2.0.1 on 2019-01-07 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0008_bookcopy_borrow_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Library')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
