# Generated by Django 2.1.7 on 2019-09-01 18:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_library_waitlist_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='waitlistitem',
            unique_together={('book', 'library', 'user')},
        ),
    ]
