version: 2
defaults: &defaults
  working_directory: ~/kamu
  docker:
    - image: circleci/python:3.7.0
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - persist_to_workspace:
          root: tmp
          paths:
            - cc-test-reporter
  security-checks:
    <<: *defaults
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: sh ci/security-checks.sh
      - store_artifacts:
          path: /tmp/artifacts/hawkeye_report.json
  backend-tests:
    <<: *defaults
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/kamu/tmp
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
      - save_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            paths:
              - "venv"
      - run:
          command: |
              . venv/bin/activate
              DJANGO_SETTINGS_MODULE=kamu.settings.test coverage run manage.py test
              coverage xml
              ./tmp/cc-test-reporter format-coverage -t coverage.py -o tmp/codeclimate.backend.json coverage.xml
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.backend.json
  frontend-tests:
    <<: *defaults
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/kamu/tmp
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run lint
      - run:
          command: |
              npm test
              ./tmp/cc-test-reporter format-coverage -t lcov -o tmp/codeclimate.frontend.json coverage/lcov.info
      - persist_to_workspace:
          root: tmp
          paths: 
            - codeclimate.frontend.json
  upload-coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/kamu/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: |
            ./tmp/cc-test-reporter sum-coverage tmp/codeclimate.*.json -p 2 -o tmp/codeclimate.total.json
            ./tmp/cc-test-reporter upload-coverage -i tmp/codeclimate.total.json
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - backend-tests:
          requires:
            - build
      - frontend-tests:
          requires: 
             - build
      - upload-coverage:
          requires:
             - backend-tests
             - frontend-tests
  nightly:
    jobs:
      - security-checks
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
