version: 2
jobs:
  security-checks:
    working_directory: ~/kamu
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: sh ci/security-checks.sh
      - store_artifacts:
          path: /tmp/artifacts/hawkeye_report.json
  build_backend:
    working_directory: ~/kamu
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
      - save_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            paths:
              - "venv"
      - run:
          command: |
              . venv/bin/activate
              coverage run manage.py test
              codeclimate-test-reporter
  build_frontend:
    working_directory: ~/kamu
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm run-script lint
      - run:
          command: npm run-script test
workflows:
  version: 2
  build_and_test:
    jobs:
      - security-checks
      - build_backend
      - build_frontend
