version: 2
jobs:
  security-checks:
    working_directory: ~/kamu
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            security-checks.sh
      - store_artifacts:
          path: /tmp/artifacts/hawkeye_report.json
  build_backend:
    working_directory: ~/kamu
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
      - save_cache:
            key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            paths:
              - "venv"
      - run:
          command: |
              . venv/bin/activate
              DISABLE_SAML2=true python manage.py test
  build_frontend:
    working_directory: ~/kamu
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          command: 'sudo npm install -g yarn@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          command: yarn test
workflows:
  version: 2
  build_and_test:
    jobs:
      - security-checks
      - build_backend
      - build_frontend
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/032e112573c8a1eafc93
