import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'webpack_loader',
    'books',
    'django_saml2_auth',
    'django_crontab',
]

CRONJOBS = [
    ('0 12 * * mon', 'books.cron.send_notification.send_borrows_out_of_time_notifications')
]

CRONTAB_COMMAND_PREFIX = 'export DISABLE_SAML2=true &&'

EMAIL_HOST='localhost'
EMAIL_PORT='2525'
EMAIL_TIMEOUT=60
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

CRON_EMAIL_NOTIFICATION_SETTINGS = {
    'TEMPLATE_FROM': 'kamu@thoughtworks.com',
    'TEMPLATE_SUBJECT': 'KAMU FRIENDLY REMINDER',    
    'TEMPLATE_BODY':  '''
        Dear User,
        Please return the book <b>{bookName}</b> you have borrowed in <b>{borrowedDate}</b>. 

        Remember the max term is <b>{maxTerm}</b> months.

        Gretings from kamu team.

        <i>Autogenerated email, please do not reply</i>
    ''',    
    'BORROW_MAX_TERM_MONTH': 3
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kamu.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages'
            ],
        },
    },
]

WSGI_APPLICATION = 'kamu.wsgi.application'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets'),
    os.path.join(BASE_DIR, 'public')
]

WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'bundles/',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
        'IGNORE': []
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'PAGE_SIZE': 10
}

if os.environ.get("DISABLE_SAML2") == None:
    SAML2_AUTH = {
        'DEFAULT_NEXT_URL': '/',
        'NEW_USER_PROFILE': {
            'USER_GROUPS': [],
            'ACTIVE_STATUS': True,
            'STAFF_STATUS': True,
            'SUPERUSER_STATUS': True,
        },
        'ATTRIBUTES_MAP': {
            'email': 'email',
            'username': 'email',
            'first_name': 'firstName',
            'last_name': 'lastName',
        }
    }
    SAML2_AUTH['METADATA_AUTO_CONF_URL'] = os.environ['OKTA_METADATA_URL']
